apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtdmspaymentinstrumentmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtdmspaymentinstrumentmanager
  template:
    metadata:
      labels:
        app: rtdmspaymentinstrumentmanager
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
    spec:
      containers:
        - name: rtdmspaymentinstrumentmanager
          image: cstaruatregistry.azurecr.io/rtdmspaymentinstrumentmanager
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: postgres-credentials
            - secretRef:
                name: azure-storage
            - configMapRef:
                name: eventhub-logging
            - configMapRef:
                name: rtdpaymentinstrumentmanager
            - configMapRef:
                name: jvm
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 30
      hostAliases:
        - hostnames:
            - bpd-event-uat.servicebus.windows.net
          ip: 10.70.67.5
